### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lequyduong98** [sartura/generic-ubus-plugin#1]
I'm trying to build ubus plugin and stuck when run "make".
here is output

> /home/osboxes/sysrepofs/repositories/plugins/generic-ubus-plugin/src/generic_ubus.c:134:18: error: ‘struct lyd_node’ has no member named ‘child’
  134 |  LY_TREE_FOR(root->child, child)
      |                  ^~
/home/osboxes/sysrepofs/repositories/plugins/generic-ubus-plugin/src/generic_ubus.c:134:33: error: expected ‘;’ before ‘{’ token
  134 |  LY_TREE_FOR(root->child, child)
      |                                 ^
      |                                 ;
  135 |  {
      |  ~                               
/home/osboxes/sysrepofs/repositories/plugins/generic-ubus-plugin/src/generic_ubus.c:145:2: warning: implicit declaration of function ‘lyd_free’; did you mean ‘ly_in_free’? [-Wimplicit-function-declaration]
  145 |  lyd_free(next);
      |  ^~~~~~~~
      |  ly_in_free
/home/osboxes/sysrepofs/repositories/plugins/generic-ubus-plugin/src/generic_ubus.c:120:19: warning: unused variable ‘node’ [-Wunused-variable]
  120 |  struct lyd_node *node = NULL;
      |                   ^~~~
/home/osboxes/sysrepofs/repositories/plugins/generic-ubus-plugin/src/generic_ubus.c:132:3: error: label ‘cleanup’ used but not defined
  132 |   goto cleanup;
      |   ^~~~
/home/osboxes/sysrepofs/repositories/plugins/generic-ubus-plugin/src/generic_ubus.c: In function ‘generic_ubus_apply_module_changes’:
/home/osboxes/sysrepofs/repositories/plugins/generic-ubus-plugin/src/generic_ubus.c:179:90: error: passing argument 7 of ‘sr_get_change_tree_next’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  179 |  while (sr_get_change_tree_next(session, it, &operation, &node, &prev_value, &prev_list, &prev_default) == SR_ERR_OK) {
      |                                                                                          ^~~~~~~~~~~~~
      |                                                                                          |
      |                                                                                          _Bool *

there are a lot of error in my out put
pls give me some help.

[output.txt](https://github.com/sartura/generic-ubus-plugin/files/7510706/output.txt)

**Comment by phongvv** [comment]
I get this error too. Pls give me some help!

**Comment by lequyduong98** [comment]
I've found the issue. It's because the version of srpo plugin. 
This issue is fixed by download "Jul 15, 2020 commit file"
